[filters.gazeangle]
function = "gazeAnglePreProcessing"

[metrics.gazeCutoutAngleDuration]
function = "gazeCutoutAngleDuration"

[metrics.gazeCutoutAngleRatio]
function = "gazeCutoutAngleRatio"

[metrics.gazeCutoutAngleViolations]
function = "gazeCutoutAngleViolations"